# Generated by Django 4.0.1 on 2022-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=30, verbose_name='Название сайта')),
                ('site_link', models.CharField(blank=True, max_length=25, verbose_name='Ссылка на сайт')),
                ('course_title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('course_link', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на курс')),
                ('certificate', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Сертификат')),
            ],
        ),
        migrations.CreateModel(
            name='PetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('site_link', models.CharField(max_length=50, verbose_name='Ссылка на сайт')),
                ('site_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('note', models.TextField(blank=True, verbose_name='Описание сайта')),
                ('homepage_photo', models.ImageField(blank=True, upload_to='pet-projects/', verbose_name='Фотка главной сайта')),
                ('git_repository', models.CharField(blank=True, max_length=50, verbose_name='GitHub')),
            ],
        ),
    ]
