# Generated by Django 4.0.1 on 2022-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='site_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка на сайт'),
        ),
    ]
